# Generated by Django 2.2.3 on 2021-05-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_auto_20210112_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservadeporte',
            options={'verbose_name': 'la reserva', 'verbose_name_plural': 'Deportes'},
        ),
        migrations.AlterModelOptions(
            name='reservahotel',
            options={'verbose_name': 'la reserva', 'verbose_name_plural': 'Cabañas'},
        ),
        migrations.AlterModelOptions(
            name='reservaplato',
            options={'verbose_name': 'la reserva', 'verbose_name_plural': 'Platos Tipicos'},
        ),
        migrations.AlterModelOptions(
            name='reservaturismo',
            options={'verbose_name': 'la reserva', 'verbose_name_plural': 'Lugares Turísticos'},
        ),
    ]
