# Generated by Django 2.2.3 on 2021-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_auto_20210604_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadeporte',
            name='visita',
            field=models.BooleanField(default=True, verbose_name='Visita'),
        ),
        migrations.AlterField(
            model_name='reservahotel',
            name='visita',
            field=models.BooleanField(default=True, verbose_name='Visita'),
        ),
        migrations.AlterField(
            model_name='reservaplato',
            name='visita',
            field=models.BooleanField(default=True, verbose_name='Visita'),
        ),
        migrations.AlterField(
            model_name='reservaturismo',
            name='visita',
            field=models.BooleanField(default=True, verbose_name='Visita'),
        ),
    ]
