# Generated by Django 2.2.3 on 2021-06-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_auto_20210606_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservadeporte',
            name='costo',
            field=models.SmallIntegerField(default=0, verbose_name='Costo de la reserva'),
        ),
        migrations.AddField(
            model_name='reservahotel',
            name='costo',
            field=models.SmallIntegerField(default=0, verbose_name='Costo de la reserva'),
        ),
        migrations.AddField(
            model_name='reservaplato',
            name='costo',
            field=models.SmallIntegerField(default=0, verbose_name='Costo de la reserva'),
        ),
        migrations.AddField(
            model_name='reservaturismo',
            name='costo',
            field=models.SmallIntegerField(default=0, verbose_name='Costo de la reserva'),
        ),
    ]
