# Generated by Django 2.2.3 on 2021-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_auto_20210609_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadeporte',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo de la reserva'),
        ),
    ]
