# Generated by Django 2.2.3 on 2021-06-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_auto_20210610_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadeporte',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=1, verbose_name='Tiempo de espera (En días)'),
        ),
        migrations.AlterField(
            model_name='reservadeporte',
            name='confirmar',
            field=models.BooleanField(default=False, verbose_name='Confirmar (Confirmación de reserva)'),
        ),
        migrations.AlterField(
            model_name='reservadeporte',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado (Eliminación lógica)'),
        ),
        migrations.AlterField(
            model_name='reservadeporte',
            name='visita',
            field=models.BooleanField(default=True, verbose_name='Visita (Turismo Visitado)'),
        ),
        migrations.AlterField(
            model_name='reservahotel',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=1, verbose_name='Tiempo de espera (En días)'),
        ),
        migrations.AlterField(
            model_name='reservahotel',
            name='confirmar',
            field=models.BooleanField(default=False, verbose_name='Confirmar (Confirmación de reserva)'),
        ),
        migrations.AlterField(
            model_name='reservahotel',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado (Eliminación lógica)'),
        ),
        migrations.AlterField(
            model_name='reservahotel',
            name='visita',
            field=models.BooleanField(default=True, verbose_name='Visita (Turismo Visitado)'),
        ),
        migrations.AlterField(
            model_name='reservaplato',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=1, verbose_name='Tiempo de espera (En días)'),
        ),
        migrations.AlterField(
            model_name='reservaplato',
            name='confirmar',
            field=models.BooleanField(default=False, verbose_name='Confirmar (Confirmación de reserva)'),
        ),
        migrations.AlterField(
            model_name='reservaplato',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado (Eliminación lógica)'),
        ),
        migrations.AlterField(
            model_name='reservaplato',
            name='visita',
            field=models.BooleanField(default=True, verbose_name='Visita (Turismo Visitado)'),
        ),
        migrations.AlterField(
            model_name='reservaturismo',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=1, verbose_name='Tiempo de espera (En días)'),
        ),
        migrations.AlterField(
            model_name='reservaturismo',
            name='confirmar',
            field=models.BooleanField(default=False, verbose_name='Confirmar (Confirmación de reserva)'),
        ),
        migrations.AlterField(
            model_name='reservaturismo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado (Eliminación lógica)'),
        ),
        migrations.AlterField(
            model_name='reservaturismo',
            name='visita',
            field=models.BooleanField(default=True, verbose_name='Visita (Turismo Visitado)'),
        ),
    ]
