# Generated by Django 2.2.3 on 2021-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_auto_20210621_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservadeporte',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Activado (Cancelado o Aceptado)'),
        ),
        migrations.AddField(
            model_name='reservahotel',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Activado (Cancelado o Aceptado)'),
        ),
        migrations.AddField(
            model_name='reservaplato',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Activado (Cancelado o Aceptado)'),
        ),
        migrations.AddField(
            model_name='reservaturismo',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Activado (Cancelado o Aceptado)'),
        ),
    ]
