# Generated by Django 2.2.3 on 2021-05-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0016_auto_20210314_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
