# Generated by Django 2.2.3 on 2021-07-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0020_auto_20210702_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='precio',
            field=models.SmallIntegerField(default=0, verbose_name='Precio'),
        ),
    ]
