# Generated by Django 2.2.3 on 2021-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0021_auto_20210702_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio'),
        ),
    ]
