# Generated by Django 2.2.3 on 2021-07-02 18:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0022_auto_20210702_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio'),
        ),
    ]
