# Generated by Django 2.2.3 on 2021-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='tipo',
            field=models.CharField(blank=True, default='notificacion', max_length=200, null=True),
        ),
    ]
