# Generated by Django 2.2.3 on 2021-07-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_auto_20210623_1723'),
        ('notificaciones', '0002_noti_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Comentario'),
        ),
    ]
