# Generated by Django 2.2.3 on 2021-07-02 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_auto_20210701_0930'),
        ('notificaciones', '0003_noti_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='reserva_deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.ReservaDeporte'),
        ),
        migrations.AddField(
            model_name='noti',
            name='solicitud',
            field=models.CharField(blank=True, default='Sin confirmar', max_length=200, null=True),
        ),
    ]
