# Generated by Django 2.2.3 on 2021-07-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0019_auto_20210621_2131'),
        ('notificaciones', '0004_auto_20210701_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noti',
            name='reserva_deporte',
        ),
        migrations.AddField(
            model_name='noti',
            name='deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deportes.Deporte'),
        ),
    ]
