# Generated by Django 2.2.3 on 2021-07-02 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0006_auto_20210621_2131'),
        ('platos', '0007_auto_20210621_2131'),
        ('turismos', '0005_auto_20210621_2131'),
        ('notificaciones', '0005_auto_20210701_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel', verbose_name='Hotel reservado'),
        ),
        migrations.AddField(
            model_name='noti',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platos.Plato', verbose_name='Plato Típico reservado'),
        ),
        migrations.AddField(
            model_name='noti',
            name='turismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turismos.Turismo', verbose_name='Lugar Turístico reservado'),
        ),
        migrations.AlterField(
            model_name='noti',
            name='deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deportes.Deporte', verbose_name='Deporte reservado'),
        ),
    ]
