# Generated by Django 2.2.3 on 2021-07-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0008_auto_20210701_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noti',
            old_name='deporte',
            new_name='reserva_deporte',
        ),
        migrations.RenameField(
            model_name='noti',
            old_name='hotel',
            new_name='reserva_hotel',
        ),
        migrations.RenameField(
            model_name='noti',
            old_name='plato',
            new_name='reserva_plato',
        ),
        migrations.RenameField(
            model_name='noti',
            old_name='turismo',
            new_name='reserva_turismo',
        ),
        migrations.RemoveField(
            model_name='noti',
            name='fecha',
        ),
    ]
