# Generated by Django 2.2.3 on 2021-07-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_auto_20210623_1723'),
        ('notificaciones', '0009_auto_20210701_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Publicacion'),
        ),
    ]
