# Generated by Django 2.2.3 on 2021-07-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0010_noti_publicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noti',
        ),
    ]
