# Generated by Django 2.2.3 on 2021-07-02 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0010_auto_20210702_0922'),
        ('reservas', '0016_auto_20210701_0930'),
        ('notificaciones', '0011_delete_noti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='notificacion', max_length=200, null=True)),
                ('solicitud', models.CharField(blank=True, default='Sin confirmar', max_length=200, null=True)),
                ('notificacion_num', models.SmallIntegerField(default=0, verbose_name='Notificacion')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado ')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicacion')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificacion')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Comentario')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Publicacion')),
                ('reserva_deporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.ReservaDeporte', verbose_name='Deporte reservado')),
                ('reserva_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.ReservaHotel', verbose_name='Hotel reservado')),
                ('reserva_plato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.ReservaPlato', verbose_name='Plato Típico reservado')),
                ('reserva_turismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.ReservaTurismo', verbose_name='Lugar Turístico reservado')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created'],
            },
        ),
    ]
