# Generated by Django 2.2.3 on 2021-07-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagehome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('imagen', smartfields.fields.ImageField(max_length=200, upload_to='imagenes/home/%Y/%m/%d/', verbose_name='Imagen')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de publicacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificacion')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
