# Generated by Django 2.2.3 on 2021-07-10 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagehome',
            options={'verbose_name': 'Imagehome', 'verbose_name_plural': 'Imagenes de home'},
        ),
        migrations.AlterField(
            model_name='imagehome',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='imagehome',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='imagehome',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
