# Generated by Django 2.2.3 on 2021-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210710_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehome',
            name='nombre',
            field=models.CharField(blank=True, default='home', max_length=200, null=True),
        ),
    ]
