# Generated by Django 2.2.3 on 2021-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_auto_20210314_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
