# Generated by Django 2.2.3 on 2021-06-04 12:20

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0005_auto_20210520_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=smartfields.fields.ImageField(default='', max_length=200, upload_to='imagenes/platos_tipicos/%Y/%m/%d/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
