# Generated by Django 2.2.3 on 2021-06-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0006_auto_20210604_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado (Eliminacón lógica)'),
        ),
    ]
