# Generated by Django 2.2.3 on 2021-07-02 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0009_auto_20210702_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='cantidad',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad (platos típicos)'),
        ),
    ]
