# Generated by Django 2.2.3 on 2021-07-03 14:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0010_plato_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='cantidad',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por unidad'),
        ),
    ]
