# Generated by Django 2.2.3 on 2021-07-10 17:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0011_auto_20210703_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='cantidad',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por unidad'),
        ),
    ]
