# Generated by Django 2.2.3 on 2021-06-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
    ]
