# Generated by Django 2.2.3 on 2021-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificacion',
            field=models.SmallIntegerField(default=0, verbose_name='Notificacion'),
        ),
    ]
