# Generated by Django 2.2.3 on 2021-06-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='solicitud',
            field=models.SmallIntegerField(default=0, verbose_name='Solicitud'),
        ),
    ]
