# Generated by Django 2.2.3 on 2021-07-01 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noti',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noti',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='noti',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificacion'),
        ),
    ]
