# Generated by Django 2.2.3 on 2021-07-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20210701_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noti',
        ),
    ]
