# Generated by Django 2.2.3 on 2021-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_auto_20210314_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
