# Generated by Django 2.2.3 on 2021-07-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0007_auto_20210702_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
