# Generated by Django 2.2.3 on 2021-07-10 17:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0008_auto_20210702_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio'),
        ),
    ]
