# Generated by Django 2.2.3 on 2021-06-04 12:20

from django.db import migrations, models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('turismos', '0003_auto_20210314_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turismo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='turismo',
            name='imagen',
            field=smartfields.fields.ImageField(default='', max_length=200, upload_to='imagenes/turismos/%Y/%m/%d/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
