# Generated by Django 2.2.3 on 2021-07-02 18:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismos', '0005_auto_20210621_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turismo',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='turismo',
            name='publico',
            field=models.BooleanField(default=True, verbose_name='Público'),
        ),
        migrations.AlterField(
            model_name='turismo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio'),
        ),
    ]
