# Generated by Django 2.2.3 on 2021-05-20 14:53

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=smartfields.fields.ImageField(blank=True, max_length=200, null=True, upload_to='imagenes/publicaciones/%Y/%m/%d/', verbose_name='Imagen'),
        ),
    ]
