# Generated by Django 2.2.3 on 2021-06-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_publicacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='modified',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='created',
            field=models.DateTimeField(verbose_name='Fecha de publicación'),
        ),
    ]
