# Generated by Django 2.2.3 on 2021-06-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_auto_20210623_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
